### ISSUE TITLE
cdms2 somehow coming from pypi instead of conda-forge channel

### ISSUE THREAD

**Issue by xylar** [conda-forge/cdms2-feedstock#31]
```
conda create -n test_cdms2 -c conda-forge python=2.7 cdms2=3.1.2
conda activate test_cdms2
conda list cdms
# packages in environment at /home/xylar/miniconda3/envs/test_cdms2:
#
# Name                    Version                   Build  Channel
cdms2                     3.0.0                    pypi_0    pypi
```

It appears that the wrong version of cdms2 is getting installed (from pypi not conda-forge).  I couldn't figure out a way of verifying the version of the files that were actually installed but @sterlingbaldwin thinks certain things should be working with `cdms2=3.1.2` that aren't working under this install.

**Comment by dnadeau4** [comment]
@xylar  This is something that came with the latest release of `conda` 4.6.x   Instead of using the version in the [meta.yaml](https://github.com/CDAT/cdms/blob/master/recipe/meta.yaml.in#L5) files, `conda` uses the version from the [setup.py](https://github.com/CDAT/cdms/blob/v3.1.2/setup.py#L20-L22) file.     

Although it says `pypi` it is really coming from `conda-forge`.   We think this is caused by having `"regrid2", "cdms2" and "MV2"` installation in the same `setup.py`.   @doutriaux1 think that when more than 1 package is installed, now `conda` thinks it has to come from `pypi`.  We are working on a solution for the next release.

This has been confusing for us too.

**Comment by xylar** [comment]
Okay, thanks! I think one good option might be to have each install separately with its own setup.py but you and @doutriaux1 will know best.

So @sterlingbaldwin, that suggests the errors I’m seeing aren’t related to the cdms2 version and we need to investigate them.
